name: Main CI

on: 
  push

jobs:
  Init_and_test:
    name: Init and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm
      - name: Initialise npm
        run: npm ci
      - name: Perform Static Analysis with ESLint
        run: npx eslint -o eslint_report.json -f json
        continue-on-error: true
      - name: Create ESLint Annotations
        uses: ataylorme/eslint-annotate-action@v3
        with:
          only-pr-files: false
      - name: Run Jest Tests
        run: npm test

    # Updated Docker Build
    - name: Build Docker Image
      run: |
        docker build -t jasonlee136tafe/jason-lee-intro-to-devops-a2:test-latest -f Dockerfiles/test.Dockerfile .

    - name: Run Docker Container to Verify Test Image
      run: |
        docker run --rm jasonlee136tafe/jason-lee-intro-to-devops-a2:test-latest npm test
  
  deploy:
    needs: Init_and_test  
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Build and Push Test Docker Image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfiles/test.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jason-lee-intro-to-devops-a2:test-latest
  
    - name: Build and Push User Docker Image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfiles/user.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jason-lee-intro-to-devops-a2:user-latest
